ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAzGMrlhXz2TjUnBY9WgoeVLKC14zHMDYca8qV
tVdKwNBnDr/04l7uOFzgsN6F0d3gVIHU6YcujzFPCzdEJYDON7AsRJlI89nfzGAx
2euQ4RaNpHrU0ChqegkwSL1MHrcHnrmTsQAvEuTeVVFnT+ktkz694+HGnRIxkcba
Q7NTvJ8vJ4VR0pmltXa7LRVzNtIMFM0+Yb4HE0xwvGlY3C0FzOhU5RBU/A9gpLNm
huDw8IKSvcl1J6tHcCa7GNilAovZFkXX96VdSLuCkiv5R+HhhvcR1BmJMh207MJy
8UNIpqCbsYbXDU6SIX76iH2Fo3FzYVcf2pgeU+D450q2PQ5k8w==
- github:poscal

hostname: n3
